version: "3.8"
services:
  db:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - internal-network
      - external-network
  test_db:
    image: postgres:12.3
    environment:
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/test_db/data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - internal-network
      - external-network

  seed:
    image: python:3.10-slim
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/.venv
    working_dir: /app
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/postgres
    command: >
      bash -c "pip install poetry && poetry config virtualenvs.create false && poetry install && PYTHONPATH=src poetry run python src/seed.py"
    networks:
      - internal-network
      - external-network

  pgadmin:
    image: dpage/pgadmin4:6.21
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - internal-network
      - external-network

  adminer:
    image: adminer
    ports:
      - "8082:8080"
    networks:
      - internal-network
      - external-network

networks:
  internal-network:
    internal: true
  external-network:

